# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb0ba3a6c24bca556c23b00d7488db6f0e4353d650bf187e6f777bc089c2772d0c330f5350319a89c8bc7efe66a55d5a6a0f9552e790b0f63345b09d224dbcaa

test:
  secret_key_base: dd77bbf2a7f3a095dd8d48ff00cacc0bfe42af367ee225344b558495560a1a5f0b6c1bb79a7bb1f3da29e4153f31443f219417ea239490cb5007b2468d36c4bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
